// Copyright (c) 2025-2026 Winyunq. All rights reserved.
#include "UmgMcpDelegates.h"

// 实例化所有静态多播委托变量
FOnUmgMcpSessionResumed FUmgMcpDelegates::OnSessionResumed;
FOnUmgMcpMessageAppended FUmgMcpDelegates::OnMessageAppended;
FOnUmgMcpSessionDeleted FUmgMcpDelegates::OnSessionDeleted;
FOnUmgMcpSessionChanged FUmgMcpDelegates::OnSessionChanged;
FOnUmgMcpInteractionModeChanged FUmgMcpDelegates::OnInteractionModeChanged;
FOnUmgMcpRequestRestoreMessageWidget FUmgMcpDelegates::OnRequestRestoreMessageWidget;

FOnUmgMcpSessionSelected FUmgMcpDelegates::OnSessionSelected;
FOnUmgMcpNewConversation FUmgMcpDelegates::OnNewConversation;
FOnUmgMcpShowHistory FUmgMcpDelegates::OnShowHistory;
FOnUmgMcpSendClicked FUmgMcpDelegates::OnSendClicked;
FOnUmgMcpInterruptClicked FUmgMcpDelegates::OnInterruptClicked;

FOnUmgMcpGetAvailableAgents FUmgMcpDelegates::OnGetAvailableAgents;
FOnUmgMcpAtAgentChanged FUmgMcpDelegates::OnAtAgentChanged;
FOnUmgMcpGetAgentAvatar FUmgMcpDelegates::OnGetAgentAvatar;
